# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(default=None, max_length=200)),
                ('service_type', models.CharField(default=None, max_length=50, null=True)),
                ('company_owner', models.CharField(default=None, max_length=50)),
                ('agent_whatsapp', models.CharField(default=None, max_length=50)),
                ('address', models.TextField(default=None, null=True)),
                ('alternative_email', models.EmailField(default=None, max_length=254, null=True)),
                ('agent_website', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linked_In', models.URLField(blank=True, null=True)),
                ('office_contact', models.CharField(default=None, max_length=50)),
                ('agent_city', models.CharField(default=None, max_length=35)),
                ('agent_state', models.CharField(default=None, max_length=35)),
                ('agent_country', models.CharField(default=None, max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCompanyRegisterationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pak_registeration_body1', models.CharField(blank=True, default=None, max_length=200)),
                ('pak_registeration_body2', models.CharField(blank=True, default=None, max_length=400)),
                ('pak_registeration_body3', models.CharField(blank=True, default=None, max_length=400)),
                ('pak_registeration_body4', models.CharField(blank=True, default=None, max_length=400)),
                ('pak_registeration_body5', models.CharField(blank=True, default=None, max_length=400)),
                ('pak_registeration_body6', models.CharField(blank=True, default=None, max_length=400)),
                ('Internatiol_registeration_body1', models.CharField(blank=True, default=None, max_length=200)),
                ('Internatiol_registeration_body2', models.CharField(blank=True, default=None, max_length=200)),
                ('Internatiol_registeration_body3', models.CharField(blank=True, default=None, max_length=200)),
                ('Internatiol_registeration_body4', models.CharField(blank=True, default=None, max_length=200)),
                ('Internatiol_registeration_body5', models.CharField(blank=True, default=None, max_length=200)),
                ('Internatiol_registeration_body6', models.CharField(blank=True, default=None, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_ratio', models.CharField(blank=True, default=None, max_length=20)),
                ('experience', models.CharField(blank=True, default=None, max_length=20)),
                ('regional_office', models.CharField(blank=True, default=None, max_length=300)),
                ('branches', models.CharField(blank=True, default=None, max_length=250)),
                ('number_of_counselors', models.CharField(blank=True, default=None, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_fee', models.CharField(blank=True, default=None, max_length=10)),
                ('language_fee', models.CharField(blank=True, default=None, max_length=10)),
                ('refusal_fee', models.CharField(blank=True, default=None, max_length=10)),
                ('Interview_fee', models.CharField(blank=True, default=None, max_length=10)),
                ('scholarshipfee', models.CharField(blank=True, default=None, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='agent_logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMobileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_contact_number', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentServicesOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_Dealing', models.CharField(default=None, max_length=250)),
                ('service_type', models.CharField(default=None, max_length=50)),
                ('language_classes', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('processing_fee', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('program_specialist', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('refusal_appeals', models.CharField(blank=True, default=None, max_length=20)),
                ('scholarships_offered', models.CharField(blank=True, default=None, max_length=20)),
                ('interview_preparation', models.CharField(blank=True, default=None, max_length=20)),
                ('travel_and_health', models.CharField(blank=True, default=None, max_length=20)),
                ('travel_arrangements', models.CharField(blank=True, default=None, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aff_budget', models.CharField(default=None, max_length=50)),
                ('budget_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default=None, max_length=50)),
                ('city_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default=None, max_length=50)),
                ('country_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HighestQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default=None, max_length=50)),
                ('qualification_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_fee', models.CharField(default=None, max_length=10)),
                ('interview_value', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_fee', models.CharField(default=None, max_length=10)),
                ('language_value', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PassingYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=50)),
                ('year_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percent', models.CharField(default=None, max_length=50)),
                ('Percent_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_fee', models.CharField(default=None, max_length=10)),
                ('processing_value', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default=None, max_length=50)),
                ('duration_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarhipFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_fee', models.CharField(default=None, max_length=10)),
                ('scholarship_value', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default=None, max_length=50)),
                ('state_value', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StdPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Gender', 'Gender'), ('male', 'male'), ('female', 'female')], default=(('Gender', 'Gender'), ('male', 'male'), ('female', 'female')), max_length=10)),
                ('age', models.CharField(default=None, max_length=10, null=True)),
                ('whatsapp', models.CharField(default=None, max_length=15, null=True)),
                ('contact_number', models.CharField(default=None, max_length=15, unique=True)),
                ('any_other_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(default=None, max_length=500, null=True)),
                ('city', models.CharField(default=None, max_length=25, null=True)),
                ('state', models.CharField(default=None, max_length=35, null=True)),
                ('nationality', models.CharField(default=None, max_length=35, null=True)),
                ('country_of_residence', models.CharField(default=None, max_length=35, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFuture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_degree', models.CharField(default=None, max_length=35, null=True)),
                ('desired_subject', models.CharField(default=None, max_length=35, null=True)),
                ('desired_country', models.CharField(default=None, max_length=35, null=True)),
                ('scholarships', models.CharField(default=None, max_length=35, null=True)),
                ('budget', models.CharField(default=None, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='students')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_language', models.CharField(choices=[('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')], default=(('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')), max_length=30, null=True)),
                ('english_language_score', models.CharField(default=None, max_length=10, null=True)),
                ('other_Language', models.CharField(choices=[('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')], default=(('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')), max_length=30, null=True)),
                ('Other_Language_score', models.CharField(default=None, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=50)),
                ('program_duration', models.CharField(max_length=20)),
                ('Insititution', models.CharField(max_length=200)),
                ('from_country', models.CharField(max_length=35)),
                ('percentage', models.CharField(max_length=10)),
                ('passing_year', models.CharField(max_length=10)),
                ('study_gap1', models.CharField(blank=True, max_length=20, null=True)),
                ('study_gap2', models.CharField(blank=True, max_length=20, null=True)),
                ('study_gap3', models.CharField(blank=True, max_length=20, null=True)),
                ('study_gap4', models.CharField(blank=True, max_length=20, null=True)),
                ('experience1', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('experience3', models.CharField(blank=True, max_length=20, null=True)),
                ('experience4', models.CharField(blank=True, max_length=20, null=True)),
                ('achievements', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=50)),
                ('subject_value', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
