# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='Interview_fee',
            field=models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='agent_whatsapp',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='company_owner',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='experience',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='interview_preparation',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='language_fee',
            field=models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='number_of_counselors',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='office_contact',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='processing',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='processing_fee',
            field=models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='program_specialist',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='refusal_appeals',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='refusal_fee',
            field=models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='scholarshipfee',
            field=models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='scholarships_offered',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='service_type',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='travel_and_health',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='travel_arrangements',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='visa_ratio',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='Other_Language_score',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='age',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='any_other_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='contact_number',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='english_language',
            field=models.CharField(choices=[('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')], default=(('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='english_language_score',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience',
            field=models.CharField(choices=[('Job Experience', 'Job Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')], default=(('Job Experience', 'Job Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('male', 'male'), ('female', 'female')], default=(('Gender', 'Gender'), ('male', 'male'), ('female', 'female')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='other_Language',
            field=models.CharField(choices=[('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')], default=(('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='passing_year',
            field=models.CharField(choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default=(('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='percentage',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='program_duration',
            field=models.CharField(choices=[('Program Duration', 'Program Duration'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], default=(('Program Duration', 'Program Duration'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='studyGap',
            field=models.CharField(choices=[('Study Gap', 'Study Gap'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')], default=(('Study Gap', 'Study Gap'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='study_gap1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='study_gap2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='study_gap3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='subject',
            field=models.CharField(choices=[('subject', 'Subject'), ('Applied Arts', 'Applied Arts'), ('Applied Mathematics', 'Applied Mathematics'), ('Applied Sciences & Professions', 'Applied Sciences & Professions'), ('Aquaculture & Fisheries', 'Aquaculture & Fisheries'), ('Arabic', 'Arabic'), ('Archaeology', 'Archaeology'), ('Architecture', 'Architecture'), ('Area & Cultural Studies', 'Area & Cultural Studies'), ('Art History', 'Art History'), ('Arts', 'Arts'), ('Arts & Design', 'Arts & Design'), ('Astronomy', 'Astronomy'), ('Audio', 'Audio'), ('Auditing', 'Auditing'), ('Automotive', 'Automotive'), ('Automotive Engineering', 'Automotive Engineering'), ('Aviation', 'Aviation'), ('Banking', 'Banking'), ('Basic Medical Sciences', 'Basic Medical Sciences'), ('Bio & Biomedical Engineering', 'Bio & Biomedical Engineering'), ('Biodiversity & Conservation', 'Biodiversity & Conservation'), ('Biology', 'Biology'), ('Biomedicine', 'Biomedicine'), ('Biotechnology', 'Biotechnology'), ('Business & Management', 'Business & Management'), ('Business Administration', 'Business Administration'), ('Business Information Systems', 'Business Information Systems'), ('Business Intelligence & Analytics', 'Business Intelligence & Analytics'), ('Business Law', 'Business Law'), ('Business Math', 'Business Math'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Child Development And Family Life', 'Child Development And Family Life'), ('Christian Studies', 'Christian Studies'), ('Civics', 'Civics'), ('Civics For Non Muslim', 'Civics For Non Muslim'), ('Civil & Private Law', 'Civil & Private Law'), ('Civil Engineering & Construction', 'Civil Engineering & Construction'), ('Climate Studies & Meteorology', 'Climate Studies & Meteorology'), ('Clinical Pathology & Serology', 'Clinical Pathology & Serology'), ('Clothing & Textile', 'Clothing & Textile'), ('Coaching', 'Coaching'), ('Cognitive Sciences', 'Cognitive Sciences'), ('Commerce', 'Commerce'), ('Commercial Geography', 'Commercial Geography'), ('Commercial Practice', 'Commercial Practice'), ('Communication Sciences', 'Communication Sciences'), ('Communications', 'Communications'), ('Complementary & Alternative Medicine', 'Complementary & Alternative Medicine'), ('Computer Science', 'Computer Science'), ('Computer Science & IT', 'Computer Science & IT'), ('Computing', 'Computing'), ('Cookery', 'Cookery'), ('Corporate Communication', 'Corporate Communication'), ('Corporate Social Responsibility', 'Corporate Social Responsibility'), ('Cosmetics', 'Cosmetics'), ('Counselling', 'Counselling'), ('Creative Writing', 'Creative Writing'), ('Criminal Law', 'Criminal Law'), ('Criminology', 'Criminology'), ('Culinary Arts', 'Culinary Arts'), ('Data Science & Big Data', 'Data Science & Big Data'), ('Dental Hygiene', 'Dental Hygiene'), ('Dentistry', 'Dentistry'), ('Design', 'Design'), ('Digital', 'Digital'), ('Earth', 'Earth'), ('Earth Sciences', 'Earth Sciences'), ('Ecology', 'Ecology'), ('Econometrics', 'Econometrics'), ('Economics of War', 'Economics of War'), ('Economics', 'Economics'), ('Education', 'Education'), ('Education & Training', 'Education & Training'), ('Educational Psychology', 'Educational Psychology'), ('Educational Research', 'Educational Research'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics', 'Electronics'), ('Electronics & Embedded Technology', 'Electronics & Embedded Technology'), ('Elementary Anatomy & Microtech', 'Elementary Anatomy & Microtech'), ('Elementary Chemistry & Chemical', 'Elementary Chemistry & Chemical'), ('Emergency & Disaster Management', 'Emergency & Disaster Management'), ('Energy & Power Engineering', 'Energy & Power Engineering'), ('Engineering', 'Engineering'), ('English', 'English'), ('English Elective', 'English Elective'), ('Entrepreneurship', 'Entrepreneurship'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Economics & Policy', 'Environmental Economics & Policy'), ('Environmental Engineering', 'Environmental Engineering'), ('Environmental Management', 'Environmental Management'), ('Ethnic Studies', 'Ethnic Studies'), ('European Law', 'European Law'), ('European Studies', 'European Studies'), ('Event Management', 'Event Management'), ('Executive MBA', 'Executive MBA'), ('Family & Consumer Science', 'Family & Consumer Science'), ('Fashion', 'Fashion'), ('Fashion, Textiles And Luxury Goods', 'Fashion, Textiles And Luxury Goods'), ('Film, Photography & Media', 'Film, Photography & Media'), ('Finance', 'Finance'), ('Financial Mathematics', 'Financial Mathematics'), ('Fine Art', 'Fine Art'), ('Food & Nutrition', 'Food & Nutrition'), ('Food Sciences', 'Food Sciences'), ('Forensic Accounting', 'Forensic Accounting'), ('Forensic Science', 'Forensic Science'), ('Forestry', 'Forestry'), ('French', 'French'), ('General Engineering & Technology', 'General Engineering & Technology'), ('General Studies & Classics', 'General Studies & Classics'), ('Geographical Information Systems', 'Geographical Information Systems'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('German', 'German'), ('Graphic Design', 'Graphic Design'), ('Hairdressing', 'Hairdressing'), ('Health & Physical Education', 'Health & Physical Education'), ('Health Informatics', 'Health Informatics'), ('Health Management', 'Health Management'), ('Health Sciences', 'Health Sciences'), ('Hematology & Blood Banking', 'Hematology & Blood Banking'), ('History', 'History'), ('History Of Modern World', 'History Of Modern World'), ('Home Management', 'Home Management'), ('Horticulture', 'Horticulture'), ('Hospitality Management', 'Hospitality Management'), ('Hospitality, Leisure & Sports', 'Hospitality, Leisure & Sports'), ('Hotel Management', 'Hotel Management'), ('Human Medicine', 'Human Medicine'), ('Human Resource Management', 'Human Resource Management'), ('Humanities', 'Humanities'), ('Hydrology & Water Management', 'Hydrology & Water Management'), ('Industrial & Systems Engineering', 'Industrial & Systems Engineering'), ('Industrial Design', 'Industrial Design'), ('Informatics & Information Sciences', 'Informatics & Information Sciences'), ('Information Technology', 'Information Technology'), ('Innovation Management', 'Innovation Management'), ('Interior', 'Interior'), ('Interior Design', 'Interior Design'), ('International Business', 'International Business'), ('International Development', 'International Development'), ('International Law', 'International Law'), ('International Relations', 'International Relations'), ('Interpreting', 'Interpreting'), ('Islamic Education', 'Islamic Education'), ('Islamic History & Culture', 'Islamic History & Culture'), ('Islamic Studies', 'Islamic Studies'), ('IT Security', 'IT Security'), ('Journalism & Media', 'Journalism & Media'), ('Landscape Architecture', 'Landscape Architecture'), ('Language Studies', 'Language Studies'), ('Law', 'Law'), ('Legal Studies', 'Legal Studies'), ('Liberal Arts', 'Liberal Arts'), ('Library Science', 'Library Science'), ('Literature', 'Literature'), ('Management, Organisation & Leadership', 'Management, Organisation & Leadership'), ('Manufacturing', 'Manufacturing'), ('Marine Engineering', 'Marine Engineering'), ('Maritime', 'Maritime'), ('Marketing', 'Marketing'), ('Materials Science & Engineering', 'Materials Science & Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics', 'Mechatronics'), ('Media Studies & Mass Media', 'Media Studies & Mass Media'), ('Medical', 'Medical'), ('Medicine & Health', 'Medicine & Health'), ('Microbiology', 'Microbiology'), ('Midwifery', 'Midwifery'), ('Military Geography', 'Military Geography'), ('Military Science', 'Military Science'), ('Mining', 'Mining'), ('Modern History', 'Modern History'), ('Modern History', 'Modern History'), ('Molecular Sciences', 'Molecular Sciences'), ('Museum Studies', 'Museum Studies'), ('Music', 'Music'), ('Music History', 'Music History'), ('Molecular Sciences', 'Molecular Sciences'), ('Museum Studies', 'Museum Studies'), ('Music', 'Music'), ('Music History', 'Music History'), ('Natural Resource Management', 'Natural Resource Management'), ('Natural Sciences & Mathematics', 'Natural Sciences & Mathematics'), ('Natural Sciences', 'Natural Sciences'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Nutrition & Dietetics', 'Nutrition & Dietetics'), ('Oil & Gas', 'Oil & Gas'), ('Organisational Behaviour', 'Organisational Behaviour'), ('Pakistan Studies', 'Pakistan Studies'), ('Pakistani Culture', 'Pakistani Culture'), ('Patent & Intellectual Property Law', 'Patent & Intellectual Property Law'), ('Pedagogy', 'Pedagogy'), ('Performing', 'Performing'), ('Persian', 'Persian'), ('Pharmaceutical', 'Pharmaceutical'), ('Pharmacy', 'Pharmacy'), ('Philosophy', 'Philosophy'), ('Philosophy & Ethics', 'Philosophy & Ethics'), ('Photography', 'Photography'), ('Psychology', 'Psychology'), ('Physics', 'Physics'), ('Physiotherapy', 'Physiotherapy'), ('Plant & Crop Sciences', 'Plant & Crop Sciences'), ('Political Science', 'Political Science'), ('Project Management', 'Project Management'), ('Public Administration', 'Public Administration'), ('Public Health', 'Public Health'), ('Public Law', 'Public Law'), ('Public Policy', 'Public Policy'), ('Public Relations', 'Public Relations'), ('Real Estate & Property Management', 'Real Estate & Property Management'), ('Recreation', 'Recreation'), ('Religious Studies & Theology', 'Religious Studies & Theology'), ('Retail Management', 'Retail Management'), ('Risk Management', 'Risk Management'), ('Robotics', 'Robotics'), ('Social Sciences', 'Social Sciences'), ('Social Welfare', 'Social Welfare'), ('Sociology', 'Sociology'), ('Soil Science', 'Soil Science'), ('Space', 'Space'), ('Special Education', 'Special Education'), ('Special Military Studies', 'Special Military Studies'), ('Sport & Recreation Statistics', 'Sport & Recreation Statistics'), ('Supply Chain Management & Logistics', 'Supply Chain Management & Logistics'), ('Sustainable Development', 'Sustainable Development'), ('Sustainable Energy', 'Sustainable Energy'), ('Taxation', 'Taxation'), ('Teaching', 'Teaching'), ('Technology Management', 'Technology Management'), ('Television', 'Television'), ('Terrorism & Security', 'Terrorism & Security'), ('Textiles', 'Textiles'), ('Theatre & Dance', 'Theatre & Dance'), ('Theology', 'Theology'), ('Tourism', 'Tourism'), ('Tourism & Leisure', 'Tourism & Leisure'), ('Toxicology', 'Toxicology'), ('Training', 'Training'), ('Translation', 'Translation'), ('Translation & Interpreting', 'Translation & Interpreting'), ('Transport Management', 'Transport Management'), ('Transportation Engineering', 'Transportation Engineering'), ('Typing', 'Typing'), ('Veterinary', 'Veterinary'), ('Veterinary Medicine', 'Veterinary Medicine'), ('Video Games & Multimedia', 'Video Games & Multimedia'), ('Visual Arts', 'Visual Arts'), ('War', 'War'), ('Web Technologies & Cloud Computing', 'Web Technologies & Cloud Computing'), ('Zoology', 'Zoology')], default=(('subject', 'Subject'), ('Applied Arts', 'Applied Arts'), ('Applied Mathematics', 'Applied Mathematics'), ('Applied Sciences & Professions', 'Applied Sciences & Professions'), ('Aquaculture & Fisheries', 'Aquaculture & Fisheries'), ('Arabic', 'Arabic'), ('Archaeology', 'Archaeology'), ('Architecture', 'Architecture'), ('Area & Cultural Studies', 'Area & Cultural Studies'), ('Art History', 'Art History'), ('Arts', 'Arts'), ('Arts & Design', 'Arts & Design'), ('Astronomy', 'Astronomy'), ('Audio', 'Audio'), ('Auditing', 'Auditing'), ('Automotive', 'Automotive'), ('Automotive Engineering', 'Automotive Engineering'), ('Aviation', 'Aviation'), ('Banking', 'Banking'), ('Basic Medical Sciences', 'Basic Medical Sciences'), ('Bio & Biomedical Engineering', 'Bio & Biomedical Engineering'), ('Biodiversity & Conservation', 'Biodiversity & Conservation'), ('Biology', 'Biology'), ('Biomedicine', 'Biomedicine'), ('Biotechnology', 'Biotechnology'), ('Business & Management', 'Business & Management'), ('Business Administration', 'Business Administration'), ('Business Information Systems', 'Business Information Systems'), ('Business Intelligence & Analytics', 'Business Intelligence & Analytics'), ('Business Law', 'Business Law'), ('Business Math', 'Business Math'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Child Development And Family Life', 'Child Development And Family Life'), ('Christian Studies', 'Christian Studies'), ('Civics', 'Civics'), ('Civics For Non Muslim', 'Civics For Non Muslim'), ('Civil & Private Law', 'Civil & Private Law'), ('Civil Engineering & Construction', 'Civil Engineering & Construction'), ('Climate Studies & Meteorology', 'Climate Studies & Meteorology'), ('Clinical Pathology & Serology', 'Clinical Pathology & Serology'), ('Clothing & Textile', 'Clothing & Textile'), ('Coaching', 'Coaching'), ('Cognitive Sciences', 'Cognitive Sciences'), ('Commerce', 'Commerce'), ('Commercial Geography', 'Commercial Geography'), ('Commercial Practice', 'Commercial Practice'), ('Communication Sciences', 'Communication Sciences'), ('Communications', 'Communications'), ('Complementary & Alternative Medicine', 'Complementary & Alternative Medicine'), ('Computer Science', 'Computer Science'), ('Computer Science & IT', 'Computer Science & IT'), ('Computing', 'Computing'), ('Cookery', 'Cookery'), ('Corporate Communication', 'Corporate Communication'), ('Corporate Social Responsibility', 'Corporate Social Responsibility'), ('Cosmetics', 'Cosmetics'), ('Counselling', 'Counselling'), ('Creative Writing', 'Creative Writing'), ('Criminal Law', 'Criminal Law'), ('Criminology', 'Criminology'), ('Culinary Arts', 'Culinary Arts'), ('Data Science & Big Data', 'Data Science & Big Data'), ('Dental Hygiene', 'Dental Hygiene'), ('Dentistry', 'Dentistry'), ('Design', 'Design'), ('Digital', 'Digital'), ('Earth', 'Earth'), ('Earth Sciences', 'Earth Sciences'), ('Ecology', 'Ecology'), ('Econometrics', 'Econometrics'), ('Economics of War', 'Economics of War'), ('Economics', 'Economics'), ('Education', 'Education'), ('Education & Training', 'Education & Training'), ('Educational Psychology', 'Educational Psychology'), ('Educational Research', 'Educational Research'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics', 'Electronics'), ('Electronics & Embedded Technology', 'Electronics & Embedded Technology'), ('Elementary Anatomy & Microtech', 'Elementary Anatomy & Microtech'), ('Elementary Chemistry & Chemical', 'Elementary Chemistry & Chemical'), ('Emergency & Disaster Management', 'Emergency & Disaster Management'), ('Energy & Power Engineering', 'Energy & Power Engineering'), ('Engineering', 'Engineering'), ('English', 'English'), ('English Elective', 'English Elective'), ('Entrepreneurship', 'Entrepreneurship'), ('Environmental Sciences', 'Environmental Sciences'), ('Environmental Economics & Policy', 'Environmental Economics & Policy'), ('Environmental Engineering', 'Environmental Engineering'), ('Environmental Management', 'Environmental Management'), ('Ethnic Studies', 'Ethnic Studies'), ('European Law', 'European Law'), ('European Studies', 'European Studies'), ('Event Management', 'Event Management'), ('Executive MBA', 'Executive MBA'), ('Family & Consumer Science', 'Family & Consumer Science'), ('Fashion', 'Fashion'), ('Fashion, Textiles And Luxury Goods', 'Fashion, Textiles And Luxury Goods'), ('Film, Photography & Media', 'Film, Photography & Media'), ('Finance', 'Finance'), ('Financial Mathematics', 'Financial Mathematics'), ('Fine Art', 'Fine Art'), ('Food & Nutrition', 'Food & Nutrition'), ('Food Sciences', 'Food Sciences'), ('Forensic Accounting', 'Forensic Accounting'), ('Forensic Science', 'Forensic Science'), ('Forestry', 'Forestry'), ('French', 'French'), ('General Engineering & Technology', 'General Engineering & Technology'), ('General Studies & Classics', 'General Studies & Classics'), ('Geographical Information Systems', 'Geographical Information Systems'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('German', 'German'), ('Graphic Design', 'Graphic Design'), ('Hairdressing', 'Hairdressing'), ('Health & Physical Education', 'Health & Physical Education'), ('Health Informatics', 'Health Informatics'), ('Health Management', 'Health Management'), ('Health Sciences', 'Health Sciences'), ('Hematology & Blood Banking', 'Hematology & Blood Banking'), ('History', 'History'), ('History Of Modern World', 'History Of Modern World'), ('Home Management', 'Home Management'), ('Horticulture', 'Horticulture'), ('Hospitality Management', 'Hospitality Management'), ('Hospitality, Leisure & Sports', 'Hospitality, Leisure & Sports'), ('Hotel Management', 'Hotel Management'), ('Human Medicine', 'Human Medicine'), ('Human Resource Management', 'Human Resource Management'), ('Humanities', 'Humanities'), ('Hydrology & Water Management', 'Hydrology & Water Management'), ('Industrial & Systems Engineering', 'Industrial & Systems Engineering'), ('Industrial Design', 'Industrial Design'), ('Informatics & Information Sciences', 'Informatics & Information Sciences'), ('Information Technology', 'Information Technology'), ('Innovation Management', 'Innovation Management'), ('Interior', 'Interior'), ('Interior Design', 'Interior Design'), ('International Business', 'International Business'), ('International Development', 'International Development'), ('International Law', 'International Law'), ('International Relations', 'International Relations'), ('Interpreting', 'Interpreting'), ('Islamic Education', 'Islamic Education'), ('Islamic History & Culture', 'Islamic History & Culture'), ('Islamic Studies', 'Islamic Studies'), ('IT Security', 'IT Security'), ('Journalism & Media', 'Journalism & Media'), ('Landscape Architecture', 'Landscape Architecture'), ('Language Studies', 'Language Studies'), ('Law', 'Law'), ('Legal Studies', 'Legal Studies'), ('Liberal Arts', 'Liberal Arts'), ('Library Science', 'Library Science'), ('Literature', 'Literature'), ('Management, Organisation & Leadership', 'Management, Organisation & Leadership'), ('Manufacturing', 'Manufacturing'), ('Marine Engineering', 'Marine Engineering'), ('Maritime', 'Maritime'), ('Marketing', 'Marketing'), ('Materials Science & Engineering', 'Materials Science & Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics', 'Mechatronics'), ('Media Studies & Mass Media', 'Media Studies & Mass Media'), ('Medical', 'Medical'), ('Medicine & Health', 'Medicine & Health'), ('Microbiology', 'Microbiology'), ('Midwifery', 'Midwifery'), ('Military Geography', 'Military Geography'), ('Military Science', 'Military Science'), ('Mining', 'Mining'), ('Modern History', 'Modern History'), ('Modern History', 'Modern History'), ('Molecular Sciences', 'Molecular Sciences'), ('Museum Studies', 'Museum Studies'), ('Music', 'Music'), ('Music History', 'Music History'), ('Molecular Sciences', 'Molecular Sciences'), ('Museum Studies', 'Museum Studies'), ('Music', 'Music'), ('Music History', 'Music History'), ('Natural Resource Management', 'Natural Resource Management'), ('Natural Sciences & Mathematics', 'Natural Sciences & Mathematics'), ('Natural Sciences', 'Natural Sciences'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Nutrition & Dietetics', 'Nutrition & Dietetics'), ('Oil & Gas', 'Oil & Gas'), ('Organisational Behaviour', 'Organisational Behaviour'), ('Pakistan Studies', 'Pakistan Studies'), ('Pakistani Culture', 'Pakistani Culture'), ('Patent & Intellectual Property Law', 'Patent & Intellectual Property Law'), ('Pedagogy', 'Pedagogy'), ('Performing', 'Performing'), ('Persian', 'Persian'), ('Pharmaceutical', 'Pharmaceutical'), ('Pharmacy', 'Pharmacy'), ('Philosophy', 'Philosophy'), ('Philosophy & Ethics', 'Philosophy & Ethics'), ('Photography', 'Photography'), ('Psychology', 'Psychology'), ('Physics', 'Physics'), ('Physiotherapy', 'Physiotherapy'), ('Plant & Crop Sciences', 'Plant & Crop Sciences'), ('Political Science', 'Political Science'), ('Project Management', 'Project Management'), ('Public Administration', 'Public Administration'), ('Public Health', 'Public Health'), ('Public Law', 'Public Law'), ('Public Policy', 'Public Policy'), ('Public Relations', 'Public Relations'), ('Real Estate & Property Management', 'Real Estate & Property Management'), ('Recreation', 'Recreation'), ('Religious Studies & Theology', 'Religious Studies & Theology'), ('Retail Management', 'Retail Management'), ('Risk Management', 'Risk Management'), ('Robotics', 'Robotics'), ('Social Sciences', 'Social Sciences'), ('Social Welfare', 'Social Welfare'), ('Sociology', 'Sociology'), ('Soil Science', 'Soil Science'), ('Space', 'Space'), ('Special Education', 'Special Education'), ('Special Military Studies', 'Special Military Studies'), ('Sport & Recreation Statistics', 'Sport & Recreation Statistics'), ('Supply Chain Management & Logistics', 'Supply Chain Management & Logistics'), ('Sustainable Development', 'Sustainable Development'), ('Sustainable Energy', 'Sustainable Energy'), ('Taxation', 'Taxation'), ('Teaching', 'Teaching'), ('Technology Management', 'Technology Management'), ('Television', 'Television'), ('Terrorism & Security', 'Terrorism & Security'), ('Textiles', 'Textiles'), ('Theatre & Dance', 'Theatre & Dance'), ('Theology', 'Theology'), ('Tourism', 'Tourism'), ('Tourism & Leisure', 'Tourism & Leisure'), ('Toxicology', 'Toxicology'), ('Training', 'Training'), ('Translation', 'Translation'), ('Translation & Interpreting', 'Translation & Interpreting'), ('Transport Management', 'Transport Management'), ('Transportation Engineering', 'Transportation Engineering'), ('Typing', 'Typing'), ('Veterinary', 'Veterinary'), ('Veterinary Medicine', 'Veterinary Medicine'), ('Video Games & Multimedia', 'Video Games & Multimedia'), ('Visual Arts', 'Visual Arts'), ('War', 'War'), ('Web Technologies & Cloud Computing', 'Web Technologies & Cloud Computing'), ('Zoology', 'Zoology')), max_length=250),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='whatsapp',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
