# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(default='0', max_length=30)),
                ('student_type', models.CharField(default='1', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='AgGroup',
        ),
    ]
