# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0002_auto_20171220_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='country_of_residence',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='agent_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='student_type',
            field=models.CharField(max_length=30),
        ),
    ]
