# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0002_auto_20180110_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='experience1',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='experience2',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='experience3',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='study_gap1',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='study_gap2',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='study_gap3',
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='passing_year',
            field=models.CharField(choices=[('Passing Year', 'Passing Year'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default=(('Passing Year', 'Passing Year'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')), max_length=250),
        ),
    ]
