# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0003_auto_20171220_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='city',
            field=models.CharField(choices=[('City', 'City'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad')], default=(('City', 'City'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad')), max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='country_of_residence',
            field=models.CharField(choices=[('Country', 'Country'), ('Pakistan', 'Pakistan'), ('India', 'India')], default=(('Country', 'Country'), ('Pakistan', 'Pakistan'), ('India', 'India')), max_length=35, null=True),
        ),
    ]
