# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0004_auto_20180112_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='english_language',
            field=models.CharField(blank=True, choices=[('English_Language', 'English_Language'), ('No Language', 'No Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Other', 'Other')], default=(('English_Language', 'English_Language'), ('No Language', 'No Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Other', 'Other')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience',
            field=models.CharField(blank=True, choices=[('No Experience', 'No Experience'), ('Job Experience', 'Job Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')], default=(('No Experience', 'No Experience'), ('Job Experience', 'Job Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='other_Language',
            field=models.CharField(blank=True, choices=[('Other Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')], default=(('Other Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='studyGap',
            field=models.CharField(blank=True, choices=[('No Gap', 'No Gap'), ('Study Gap', 'Study Gap'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')], default=(('No Gap', 'No Gap'), ('Study Gap', 'Study Gap'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')), max_length=250, null=True),
        ),
    ]
