# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0004_auto_20171220_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualifications',
            name='from_country',
            field=models.CharField(choices=[('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')], default=(('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')), max_length=35),
        ),
        migrations.AlterField(
            model_name='studentqualifications',
            name='highest_qualification',
            field=models.CharField(choices=[('Degree', 'Degree'), ('MA', 'MA'), ('BA', 'BA')], default=(('Degree', 'Degree'), ('MA', 'MA'), ('BA', 'BA')), max_length=35),
        ),
        migrations.AlterField(
            model_name='studentqualifications',
            name='program_duration',
            field=models.CharField(choices=[('Program_Duration', 'Program_Duration'), ('16 Years', '16 Years'), ('14 Years', '14Years')], default=(('Program_Duration', 'Program_Duration'), ('16 Years', '16 Years'), ('14 Years', '14Years')), max_length=20),
        ),
        migrations.AlterField(
            model_name='studentqualifications',
            name='subject',
            field=models.CharField(choices=[('Subject', 'Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')], default=(('Subject', 'Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')), max_length=50),
        ),
    ]
