# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0005_auto_20171220_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfuture',
            name='desired_country',
            field=models.CharField(choices=[('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')], default=(('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')), max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='studentfuture',
            name='desired_degree',
            field=models.CharField(choices=[('Desired Degree', 'Desired Degree'), ('MA', 'MA'), ('BA', 'BA')], default=(('Desired Degree', 'Desired Degree'), ('MA', 'MA'), ('BA', 'BA')), max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='studentfuture',
            name='desired_subject',
            field=models.CharField(choices=[('Desired Subject', 'Desired Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')], default=(('Desired Subject', 'Desired Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')), max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='studentfuture',
            name='scholarships',
            field=models.CharField(choices=[('Scholarships', 'Scholarships'), ('Yes', 'Yes'), ('No', 'No')], default=(('Scholarships', 'Scholarships'), ('Yes', 'Yes'), ('No', 'No')), max_length=35, null=True),
        ),
    ]
