# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0006_auto_20171220_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualifications',
            name='highest_qualification',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Matriculation', 'Matriculation'), ('O-Level', 'O-Level'), ('MA', 'MA'), ('BA', 'BA')], default=(('Degree', 'Degree'), ('Matriculation', 'Matriculation'), ('O-Level', 'O-Level'), ('MA', 'MA'), ('BA', 'BA')), max_length=35),
        ),
        migrations.AlterField(
            model_name='studentqualifications',
            name='passing_year',
            field=models.CharField(choices=[('1990', '1990'), ('1991', '1991')], default=(('1990', '1990'), ('1991', '1991')), max_length=10),
        ),
        migrations.AlterField(
            model_name='studentqualifications',
            name='subject',
            field=models.CharField(choices=[('Subject', 'Subject'), ('Science Group', 'Science Group'), ('Physics', 'Physics'), ('Engineering', 'Engineering')], default=(('Subject', 'Subject'), ('Science Group', 'Science Group'), ('Physics', 'Physics'), ('Engineering', 'Engineering')), max_length=50),
        ),
    ]
