# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0007_auto_20171227_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentqualifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='desired_country',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='desired_degree',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='desired_subject',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='scholarships',
        ),
        migrations.RemoveField(
            model_name='studentlanguage',
            name='Other_Language_score',
        ),
        migrations.RemoveField(
            model_name='studentlanguage',
            name='english_language',
        ),
        migrations.RemoveField(
            model_name='studentlanguage',
            name='english_language_score',
        ),
        migrations.RemoveField(
            model_name='studentlanguage',
            name='other_Language',
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='Insititution',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='Other_Language_score',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='achievements',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='budget',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='desired_country',
            field=models.CharField(choices=[('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')], default=(('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')), max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='desired_degree',
            field=models.CharField(choices=[('Desired Degree', 'Desired Degree'), ('MA', 'MA'), ('BA', 'BA')], default=(('Desired Degree', 'Desired Degree'), ('MA', 'MA'), ('BA', 'BA')), max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='desired_subject',
            field=models.CharField(choices=[('Desired Subject', 'Desired Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')], default=(('Desired Subject', 'Desired Subject'), ('Physics', 'Physics'), ('Engineering', 'Engineering')), max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='english_language',
            field=models.CharField(choices=[('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')], default=(('English_Language', 'English_Language'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Oher', 'Oher')), max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='english_language_score',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='experience1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='experience3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='experience4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='from_country',
            field=models.CharField(choices=[('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')], default=(('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')), max_length=35),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='highest_qualification',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Matriculation', 'Matriculation'), ('O-Level', 'O-Level'), ('MA', 'MA'), ('BA', 'BA')], default=(('Degree', 'Degree'), ('Matriculation', 'Matriculation'), ('O-Level', 'O-Level'), ('MA', 'MA'), ('BA', 'BA')), max_length=35),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='other_Language',
            field=models.CharField(choices=[('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')], default=(('Other_Language', 'Other Language'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French ', 'French '), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('Portoguese', 'Portoguese'), ('Korian', 'Korian'), ('Oher', 'Oher')), max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='passing_year',
            field=models.CharField(choices=[('1990', '1990'), ('1991', '1991')], default=(('1990', '1990'), ('1991', '1991')), max_length=10),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='percentage',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='program_duration',
            field=models.CharField(choices=[('Program_Duration', 'Program_Duration'), ('16 Years', '16 Years'), ('14 Years', '14Years')], default=(('Program_Duration', 'Program_Duration'), ('16 Years', '16 Years'), ('14 Years', '14Years')), max_length=20),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='scholarships',
            field=models.CharField(choices=[('Scholarships', 'Scholarships'), ('Yes', 'Yes'), ('No', 'No')], default=(('Scholarships', 'Scholarships'), ('Yes', 'Yes'), ('No', 'No')), max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='study_gap1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='study_gap2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='study_gap3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='study_gap4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stdpersonalinfo',
            name='subject',
            field=models.CharField(choices=[('Subject', 'Subject'), ('Science Group', 'Science Group'), ('Physics', 'Physics'), ('Engineering', 'Engineering')], default=(('Subject', 'Subject'), ('Science Group', 'Science Group'), ('Physics', 'Physics'), ('Engineering', 'Engineering')), max_length=50),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='country_of_residence',
            field=models.CharField(choices=[('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')], default=(('Country', 'Country'), ('Australia', 'Australia'), ('USA', 'USA')), max_length=35, null=True),
        ),
        migrations.DeleteModel(
            name='StudentQualifications',
        ),
    ]
