# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0008_auto_20180112_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='alternative_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='office_contact',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
