# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0008_auto_20171229_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body1',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body2',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body3',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body4',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body5',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='Internatiol_registeration_body6',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body1',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body2',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body3',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body4',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body5',
        ),
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='pak_registeration_body6',
        ),
        migrations.RemoveField(
            model_name='agentexpertise',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='agentexpertise',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='agentexpertise',
            name='number_of_counselors',
        ),
        migrations.RemoveField(
            model_name='agentexpertise',
            name='regional_office',
        ),
        migrations.RemoveField(
            model_name='agentexpertise',
            name='visa_ratio',
        ),
        migrations.RemoveField(
            model_name='agentfees',
            name='Interview_fee',
        ),
        migrations.RemoveField(
            model_name='agentfees',
            name='language_fee',
        ),
        migrations.RemoveField(
            model_name='agentfees',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='agentfees',
            name='refusal_fee',
        ),
        migrations.RemoveField(
            model_name='agentfees',
            name='scholarshipfee',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='countries_Dealing',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='interview_preparation',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='language_classes',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='program_specialist',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='refusal_appeals',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='scholarships_offered',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='travel_and_health',
        ),
        migrations.RemoveField(
            model_name='agentservicesoffered',
            name='travel_arrangements',
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body1',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body2',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body3',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body4',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body5',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Internatiol_registeration_body6',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='Interview_fee',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='branches',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='countries_Dealing',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='experience',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='interview_preparation',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='language_classes',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='language_fee',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='number_of_counselors',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body1',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body2',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body3',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body4',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body5',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body6',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='processing',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='processing_fee',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='program_specialist',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='refusal_appeals',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='refusal_fee',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='regional_office',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='scholarshipfee',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='scholarships_offered',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='travel_and_health',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='travel_arrangements',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='visa_ratio',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='service_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
