# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0009_auto_20180112_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body1',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body2',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='pak_registeration_body3',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='service_type',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
