# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0011_auto_20180117_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='Interview_fee',
            field=models.CharField(choices=[('Interview Fees', 'Interview Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('Interview Fees', 'Interview Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='countries_Dealing',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='experience',
            field=models.CharField(choices=[('Experience', 'Experience'), ('No Experience', 'No Experience'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('More Than 10 Years', 'More Than 10 Years')], default=(('Experience', 'Experience'), ('No Experience', 'No Experience'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('More Than 10 Years', 'More Than 10 Years')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='interview_preparation',
            field=models.CharField(choices=[('Interview Preparation', 'Interview Preparation'), ('Yes', 'Yes'), ('No', 'No')], default=(('Interview Preparation', 'Interview Preparation'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='language_fee',
            field=models.CharField(choices=[('Language Fees', 'Language Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('Language Fees', 'Language Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='number_of_counselors',
            field=models.CharField(choices=[('Number of Counselors', 'Number of Counselors'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50')], default=(('Number of Counselors', 'Number of Counselors'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='processing_fee',
            field=models.CharField(choices=[('Processing Fee', 'Processing Fee'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('Processing Fee', 'Processing Fee'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='refusal_appeals',
            field=models.CharField(choices=[('Refusal Appeals', 'Refusal Appeals'), ('Yes', 'Yes'), ('No', 'No')], default=(('Refusal Appeals', 'Refusal Appeals'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='refusal_fee',
            field=models.CharField(choices=[('Refusal Fee', 'Refusal Fee'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('Refusal Fee', 'Refusal Fee'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='regional_office',
            field=models.CharField(choices=[('Regional Office', 'Regional Office'), ('Yes', 'Yes'), ('No', 'No')], default=(('Regional Office', 'Regional Office'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='scholarshipfee',
            field=models.CharField(choices=[('Scholarship Fees', 'Scholarship Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')], default=(('Scholarship Fees', 'Scholarship Fees'), ('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15000', '10,000-15000'), ('15000-20,000', '15000-20,000'), ('20,000-25000', '20,000-25000'), ('25000-30,000', '25000-30,000'), ('30,000-35000', '30,000-35000'), ('35000-40,000', '35000-40,000'), ('40,000-45000', '40,000-45000'), ('45000-50,000', '45000-50,000'), ('50,000-60,000', '50,000-60,000'), ('60,000-70,000', '60,000-70,000'), ('70,000-80,000', '70,000-80,000'), ('80,000-90,000', '80,000-90,000'), ('90,000-100,000', '90,000-100,000'), ('100,000-125,000', '100,000-125,000'), ('125,000-150,000', '125,000-150,000'), ('150,000-200,000', '150,000-200,000')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='scholarships_offered',
            field=models.CharField(choices=[('Scholarships Offered', 'Scholarships Offered'), ('Yes', 'Yes'), ('No', 'No')], default=(('Scholarships Offered', 'Scholarships Offered'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='travel_and_health',
            field=models.CharField(choices=[('Travel and Health Insurance', 'Travel and Health Insurance'), ('Yes', 'Yes'), ('No', 'No')], default=(('Travel and Health Insurance', 'Travel and Health Insurance'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='travel_arrangements',
            field=models.CharField(choices=[('Travel Arrangements', 'Travel Arrangements'), ('Yes', 'Yes'), ('No', 'No')], default=(('Travel Arrangements', 'Travel Arrangements'), ('Yes', 'Yes'), ('No', 'No')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agentcompanyinfo',
            name='visa_ratio',
            field=models.CharField(choices=[('Visa Success Ratio', 'Visa Success Ratio'), ('35%', '35%'), ('40%', '40%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], default=(('Visa Success Ratio', 'Visa Success Ratio'), ('35%', '35%'), ('40%', '40%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='desired_country',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='experience',
            field=models.CharField(blank=True, choices=[('Job Experience', 'Job Experience'), ('No Experience', 'No Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')], default=(('Job Experience', 'Job Experience'), ('No Experience', 'No Experience'), ('1 - Month to 3-Months', '1- Month to 3-Months'), ('3- Month to 6-Months', '3- Month to 6-Months'), ('1-Year to 1.5-Years', '1-Year to 1.5-Yeara'), ('1.5-Year to 2 Years', '1.5-Year to 2 Years'), ('2-Years to 2.5-Years', '2-Years to 2.5-Years'), ('2.5-Years to 3-Years', '2.5-Years to 3-Years'), ('3-Years to 3.5-Years', '3-Years to 3.5-Years'), ('4-Years to 4.5-Years', '4-Years to 4.5-Years'), ('4.5-Years to 5-Years', '4.5-Years to 5-Years'), ('5-Years to 5.5-Years', '5-Years to 5.5-Years'), ('5.5-Years to 6-Years', '5.5-Years to 6-Years'), ('6-Years to 6.5-Years', '6-Years to 6.5-Years'), ('6.5-Years to 7-Years', '6.5-Years to 7-Years'), ('7-Years to 7.5-Years', '7-Years to 7.5-Years'), ('7.5-Years to 8-Years', '7.5-Years to 8-Years'), ('8-Years to 8.5-Years', '8-Years to 8.5-Years'), ('8.5-Years to 9-Years', '8.5-Years to 9-Years'), ('9-Years to 9.5-Years', '9-Years to 9.5-Years'), ('9.5-Years to 10-Years', '9.5-Years to 10-Years'), ('Other', 'Other')), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='from_country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='passing_year',
            field=models.CharField(choices=[('Passing Year', 'Passing Year'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default=(('Passing Year', 'Passing Year'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('1996', '1996'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')), max_length=500),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='percentage',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('35%', '35%'), ('40%', '40%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], default=(('Percentage', 'Percentage'), ('35%', '35%'), ('40%', '40%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')), max_length=500),
        ),
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='program_duration',
            field=models.CharField(choices=[('Program Duration', 'Program Duration'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], default=(('Program Duration', 'Program Duration'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')), max_length=500),
        ),
    ]
