# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0014_auto_20180109_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='experience4',
        ),
        migrations.RemoveField(
            model_name='stdpersonalinfo',
            name='study_gap4',
        ),
    ]
