# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0015_auto_20180109_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdpersonalinfo',
            name='country_of_residence',
            field=models.CharField(choices=[('Country of Residence', 'Country of Residence'), ('Pakistan', 'Pakistan'), ('Australia', 'Australia')], default=(('Country of Residence', 'Country of Residence'), ('Pakistan', 'Pakistan'), ('Australia', 'Australia')), max_length=35),
        ),
    ]
