# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0019_auto_20180127_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcompanyinfo',
            name='countries_Dealing',
        ),
        migrations.AddField(
            model_name='agentcompanyinfo',
            name='countries_Dealing',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
