# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0022_auto_20180206_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcompanyregisterationinfo',
            name='count',
        ),
    ]
