# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0023_remove_agentcompanyregisterationinfo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcompanyregisterationinfo',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudyAims.Country_Deal'),
            preserve_default=False,
        ),
    ]
