# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyAims', '0024_agentcompanyregisterationinfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmobilenumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='CityList',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='HighestQualification',
        ),
        migrations.DeleteModel(
            name='InterviewFees',
        ),
        migrations.DeleteModel(
            name='Language_Fees',
        ),
        migrations.DeleteModel(
            name='PassingYear',
        ),
        migrations.DeleteModel(
            name='Percentage',
        ),
        migrations.DeleteModel(
            name='Processing',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProgramDuration',
        ),
        migrations.DeleteModel(
            name='ScholarhipFees',
        ),
        migrations.DeleteModel(
            name='StateList',
        ),
        migrations.RemoveField(
            model_name='studentfuture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubjectList',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.DeleteModel(
            name='AgentMobileNumber',
        ),
        migrations.DeleteModel(
            name='StudentFuture',
        ),
        migrations.DeleteModel(
            name='StudentImage',
        ),
    ]
